# i am going to create a calculator using Tkinter
from tkinter import *
from PIL import Image,ImageTk
def click(event):
    global scvalue
    text=event.widget.cget("text")
    print(text)
    if text=="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else :
            value=eval(e1.get())
        scvalue.set(value)
        e1.update()
        
    elif text=="C":
        scvalue.set("")
        e1.update()
    else :
        scvalue.set(scvalue.get() + text)
        e1.update()
win=Tk()
win.geometry("430x370")
win.resizable(0,0)
win.config(background="black")
win.title("calculator")
logo=PhotoImage(file="C:\\Users\\rk751\\Downloads\\calculator.png")
win.iconphoto(0,logo)
scvalue=StringVar()
scvalue.set("")
e1=Entry(win,font=("algerian",25,"bold"),textvar=scvalue,bg="white",fg="black",bd=15,justify="right",width=35)
e1.pack()
b1=Button(win,text="7",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b1.place(x=10,y=80)
b1.bind("<Button-1>",click)
b2=Button(win,text="8",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b2.place(x=115,y=80)
b2.bind("<Button-1>",click)
b3=Button(win,text="9",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b3.place(x=220,y=80)
b3.bind("<Button-1>",click)
b4=Button(win,text="+",font=("lucida",18,"bold"),bg="white",fg="black",bd=10,width=5)
b4.place(x=325,y=80)
b4.bind("<Button-1>",click)
b5=Button(win,text="4",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b5.place(x=10,y=150)
b5.bind("<Button-1>",click)
b6=Button(win,text="5",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b6.place(x=115,y=150)
b6.bind("<Button-1>",click)
b7=Button(win,text="6",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b7.place(x=220,y=150)
b7.bind("<Button-1>",click)
b8=Button(win,text="-",font=("lucida",18,"bold"),bg="white",fg="black",bd=10,width=5)
b8.place(x=325,y=150)
b8.bind("<Button-1>",click)
b9=Button(win,text="1",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b9.place(x=10,y=220)
b9.bind("<Button-1>",click)
b10=Button(win,text="2",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b10.place(x=115,y=220)
b10.bind("<Button-1>",click)
b11=Button(win,text="3",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b11.place(x=220,y=220)
b11.bind("<Button-1>",click)
b12=Button(win,text="*",font=("licida",18,"bold"),bg="white",fg="black",bd=10,width=5)
b12.place(x=325,y=220)
b12.bind("<Button-1>",click)
b13=Button(win,text="0",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b13.place(x=10,y=290)
b13.bind("<Button-1>",click)
b14=Button(win,text="=",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b14.place(x=115,y=290)
b14.bind("<Button-1>",click)
b15=Button(win,text="C",font=("lucida",18,"bold"),bg="white",fg="black",bd=10,width=5)
b15.place(x=220,y=290)
b15.bind("<Button-1>",click)
b16=Button(win,text="/",font=("algerian",18,"bold"),bg="white",fg="black",bd=10,width=5)
b16.place(x=325,y=290)
b16.bind("<Button-1>",click)
win.mainloop()
