#login system
from tkinter import *
from tkinter import messagebox,ttk
from PIL import Image,ImageTk
import mysql.connector as sql
mycon=sql.connect(host="localhost",user="root",password="root",database="hubnet")
mycur=mycon.cursor()
win=Tk()              
win.geometry('500x500')
win.resizable(0,0)
win.title("HSMS")
win.config(background="blue")
cb=IntVar()
name=StringVar()
email=StringVar()
password=StringVar()
sid=StringVar()
mobile_no=StringVar()
course=StringVar()
def cbs():
    if cb.get()==1:
        b1['state']=ACTIVE
        b2['state']=ACTIVE
        b3['state']=ACTIVE
    else :
        b1['state']=DISABLED
        b2['state']=DISABLED
        b3['state']=DISABLED
def signup():
    n=name.get()
    e=email.get()
    p=password.get()
    q="insert into login values('{}','{}','{}')".format(n,e,p)
    mycur.execute(q)
    mycon.commit()
    messagebox.showinfo("saved","record save succesfully")
    e=StringVar()
    p=StringVar()
    
def signin():
    em=email.get()
    pa=password.get()
    import mysql.connector as sql
    mycon=sql.connect(host="localhost",user="root",password="root",database="hubnet")
    mycur=mycon.cursor()
    q="select * from login where emailid ='{}' and password ='{}' ".format(em,pa)
    mycur.execute(q)
    rec=mycur.fetchone()
    if rec==None:
         messagebox.showinfo("not match","emailid or password invalid")
    else :
        messagebox.showinfo("Record match","signin successfully")
        win1=Toplevel(win)
        win1.geometry("500x500")
        win1.resizable(0,0)
        win1.config(background="lightgreen")
        l1=Label(win1,text="Hubnet student management",bg="lightgreen",fg="black",font=('algerian',18,"bold"),bd=5)
        l1.pack(padx=0,pady=5)
        def find():
            win2=Toplevel(win1)
            sid=StringVar()
            def view():
                si=sid.get()
                mycon=sql.connect(host="localhost",user="root",password="root",database="hubnet")
                mycur=mycon.cursor()
                q="select * from student where sid='{}'".format(si)
                mycur.execute(q)
                mycur.fetchone()
                if sid=="{}" :
                    print(sid)
                    messagebox.showinfo("Record found","record found successfully")
                else :
                    messagebox.showinfo("record not found","not found")
            win2.geometry("400x400")
            win2.resizable(0,0)
            win2.config(background="lightgreen")
            sid=StringVar()
            l1=Label(win2,text="ENTER SID",bg="lightgreen",fg="black",font=('algerian',18,"bold"),bd=5)
            l1.place(x=150,y=80)
            e1=Entry(win2,font=("algerian",14,'bold'),fg="black",bg="white",bd=4)
            e1.place(x=100,y=120)
            b1=Button(win2,text="view",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=view)
            b1.place(x=150,y=200)
            win2.mainloop()
        def admission():
            win=Toplevel(win1)
            win.geometry("500x500")
            win.resizable(0,0)
            win.config(background="lightgreen")
            l1=Label(win,text="Hubnet student management",bg="lightgreen",fg="black",font=('algerian',18,"bold"),bd=5)
            l1.pack(padx=0,pady=5)
            l2=Label(win,text="sid :",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l2.place(x=20,y=70)
            e1=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=sid)
            e1.place(x=140,y=70)
            l3=Label(win,text="Name :",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l3.place(x=20,y=120)
            e2=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=name)
            e2.place(x=140,y=120)
            l4=Label(win,text="mob_No :",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l4.place(x=20,y=170)
            e3=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=mobile_no)
            e3.place(x=140,y=170)
            l5=Label(win,text="course",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l5.place(x=20,y=220)
            e4=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=course)
            e4.place(x=140,y=220)
            def savedata():
                sa=sid.get()
                sn=name.get()
                sm=mobile_no.get()
                sc=course.get()
                mycon=sql.connect(host="localhost",user="root",password="root",database="hubnet")
                mycur=mycon.cursor()
                q="insert into student values('{}','{}','{}','{}')".format(sa,sn,sm,sc)
                mycur.execute(q)
                mycon.commit()
                messagebox.showinfo("Record saved","Record add successfully")
            b1=Button(win,text='Save',bg='green',fg='black',font=('algerian',14,'bold'),bd=5,command=savedata)
            b1.place(x=70,y=300)
            win.mainloop()
        def update():
            win=Toplevel(win1)
            sname=StringVar()
            smobile=StringVar()
            scourse=StringVar()
            def change():
                sa=sid.get()
                sn=sname.get()
                sm=smobile.get()
                sc=scourse.get()
                q="update student set name='{}',mobile_no='{}',course='{}' where sid='{}' ".format(sn,sm,sc,sa)
                mycur.execute(q)
                mycon.commit()
                messagebox.showinfo("Record update","Record update successfully")
            win.title("update")
            win.geometry("500x500")
            win.resizable(0,0)
            win.config(background="lightgreen")
            l1=Label(win,text="updating",bg="lightgreen",fg="black",font=('algerian',18,"bold"),bd=5)
            l1.pack(padx=0,pady=5)
            l2=Label(win,text="sid :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l2.place(x=20,y=70)
            e1=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=sid)
            e1.place(x=140,y=70)
            l3=Label(win,text="Name :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l3.place(x=20,y=120)
            e2=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=sname)
            e2.place(x=140,y=120)
            l4=Label(win,text="mob_No :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l4.place(x=20,y=170)
            e3=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=smobile)
            e3.place(x=140,y=170)
            l5=Label(win,text="course",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l5.place(x=20,y=220)
            e4=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=scourse)
            e4.place(x=140,y=220)
            b1=Button(win,text='update',bg='green',fg='black',font=('algerian',14,'bold'),bd=5,command=change)
            b1.place(x=70,y=300)
            win.mainloop()
        def delete():
            win=Toplevel(win1)
            sid=StringVar()
            def deletedata():
                sa=sid.get()
                mycon=sql.connect(host="localhost",user="root",password="root",database="hubnet")
                mycur=mycon.cursor()
                q="delete from student where sid='{}' ".format(sa)
                mycur.execute(q)
                mycon.commit()
                messagebox.showinfo("Record delete","Record delete successfully")
            win.geometry("500x500")
            win.resizable(0,0)
            win.config(background="lightgreen")
            l2=Label(win,text="sid :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l2.place(x=20,y=70)
            e1=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=sid)
            e1.place(x=140,y=70)
            b1=Button(win,text='delete',bg='green',fg='black',font=('algerian',14,'bold'),bd=5,command=deletedata)
            b1.place(x=70,y=150)
            win.mainloop()
        b1=Button(win1,text="Find",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=find)
        b1.place(x=320,y=80)
        b2=Button(win1,text="New Admission",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=admission)
        b2.place(x=320,y=130)
        b3=Button(win1,text="Update",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=update)
        b3.place(x=320,y=180)
        b4=Button(win1,text="Delete",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=delete)
        b4.place(x=320,y=230)
        win1.mainloop()
def forgotpassword():
    win1=Toplevel(win)
    emailid=StringVar()
    password=StringVar()
    def newpassword():
        p=password.get()
        e=emailid.get()
        import mysql.connector as sql
        mycon=sql.connect(host="localhost",user="root",password="root",database="hubnet")
        mycur=mycon.cursor()
        q="update login set password='{}' where emailid='{}'".format(p,e)
        mycur.execute(q)
        mycon.commit()
        messagebox.showinfo("save password","saved password successfully")
    win1.geometry("400x400")
    win1.resizable(0,0)
    win1.config(background="lightgreen")
    l1=Label(win1,text=" Email_Id :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l1.place(x=60,y=70)
    e3=Entry(win1,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=20,textvariable=emailid)
    e3.place(x=20,y=100)
    l2=Label(win1,text=" New Password :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l2.place(x=60,y=170)
    e3=Entry(win1,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=20,show="*",textvariable=password)
    e3.place(x=20,y=200)
    b3=Button(win1,text="new password save",font=("algerian",10),bg="blue",fg="white",bd=5,command=newpassword)
    b3.place(x=70,y=250)
    win.mainloop()
l1=Label(win,text="Hubnet Login System",bg="blue",fg="white",font=('algerian',18,"bold"),bd=5)
l1.pack(padx=0,pady=5)
image=Image.open("C:\\Users\\rk751\\OneDrive\\Desktop\\hubnet-logo.png")
im=image.resize((40,30))
im=ImageTk.PhotoImage(im)
l7=Label(win,image=im)
l7.pack()
l2=Label(win,text="username",bg="blue",fg="white",font=('algerian',16,'bold'),bd=5)
l2.place(x=160,y=80)
e1=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=name)
e1.place(x=80,y=110)
l3=Label(win,text="EmailId",bg="blue",fg="white",font=('algerian',16,'bold'),bd=5)
l3.place(x=160,y=170)
e2=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=email)
e2.place(x=80,y=200)
l4=Label(win,text="Password",bg="blue",fg="white",font=('algerian',16,'bold'),bd=5)
l4.place(x=160,y=250)
e3=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,show="*",textvariable=password)
e3.place(x=80,y=280)
c1=Checkbutton(win,text="all terms and condition are true",font=("algerian",10),bg="blue",fg="black",variable=cb,onvalue=1,offvalue=0,command=cbs)
c1.place(x=50,y=330)
b1=Button(win,text="SingIn",font=("algerian",10),bg="green",fg="white",bd=5,state="disabled",command=signup)
b1.place(x=60,y=380)
b2=Button(win,text="SingUp",font=("algerian",10),bg="green",fg="white",bd=5,state="disabled",command=signin)
b2.place(x=200,y=380)
b3=Button(win,text="Forgot Password",font=("algerian",10),bg="green",fg="white",bd=5,state="disabled",command=forgotpassword)
b3.place(x=340,y=380)
l5=Label(win,text="2nd floor,jjcomplex,E Boring canal Rd,opposite of Bharat petroleum,",font=("algerian",8),bg="blue",fg="white")
l5.place(x=40,y=450)
l6=Label(win,text="Nageshwar colony,Pandooi kothi,patna,bihar 800001",font=("algerian",8),bg="blue",fg="white")
l6.place(x=60,y=465)

win.mainloop()
